export { default as Navbar } from './navbar/Navbar';
export { default as Header } from './header/Header';
export { default as Category} from './category/Category';
export { default as Latest } from './latest/Latest';
export { default as NineItems } from './nineItems/NineItems';
export { default as CategoryResult } from './categoryResult/CategoryResult';
export { default as ArticleNavbar } from './aNavbar/ANavbar';
export { default as ArticleHeaderA } from './headerA/HeaderA';
export { default as ArticleHeaderB } from './headerB/HeaderB';
export { default as ArticleHeaderC } from './headerC/HeaderC';
export { default as ArticleSectionA } from './sectionA/SectionA';
export { default as ArticleSectionB } from './sectionB/SectionB';
export { default as ArticleSectionC } from './sectionC/SectionC';
